// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: proto/google/api/annotations.proto

/* eslint-disable */

export const protobufPackage = "spilot.api.v1";
