// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectServer(arg1, arg2) {
  return window['go']['driver']['GrpcDriver']['ConnectServer'](arg1, arg2);
}

export function GetServerStatus() {
  return window['go']['driver']['GrpcDriver']['GetServerStatus']();
}

export function Startup(arg1) {
  return window['go']['driver']['GrpcDriver']['Startup'](arg1);
}
