// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';
import {context} from '../models';
import {apiv1} from '../models';

export function ConnectServer(arg1:net.IP,arg2:string):Promise<boolean>;

export function GetServerStatus(arg1:context.Context):Promise<apiv1.GetStatusResponse>;

export function Startup(arg1:context.Context):Promise<void>;
